config/routes.rb
Gallery::Application.routes.draw do
  resources :paintings
  root to: 'paintings#index'
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name
  mount_uploader :image, ImageUploader
  
  before_create :default_name
  
  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.create(params[:painting])
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to paintings_url, notice: "Painting was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to paintings_url, notice: "Painting was successfully destroyed."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Painting Gallery</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>
      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <p>
    <%= f.file_field :image %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div class="painting">
  <%= link_to image_tag(painting.image_url(:thumb)), painting if painting.image? %>
  <div class="name"><%= painting.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_painting_path(painting) %> |
    <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#paintings").append("<%= j render(@painting) %>");
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>


<% @paintings.each do |p| %>
	<tr>
		<td><%#= "/uploads"+url_for(p)+"/image.jpg" %></td>
		<td><%#= painting_url(p) %></td>
		
		<%#= link_to(image_tag("photo a loader" , :title => "ok"), a.to_s , :class => "grouped_images", :rel => "group1") %>
		<td><%#= link_to(image_tag(p.image.url(:thumb) , :title => "ok"), p.image.url(:thumb).to_s, :class => "grouped_images", :rel => "group1") %></td>
		<%#= p.name %>
		<%#= p.image %>
		<%#= a.to_s %>
		
		
		<td>
		<% if p.image_url(:big) %>
			<%= link_to(image_tag(p.image.url(:thumb) , :title => "ok"), p.image.url(:big).to_s, :class => "grouped_images", :rel => "group1") %>
		<% else %>
			<%= link_to(image_tag(p.image.url(:thumb) , :title => "ok"), p.image.url(:thumb).to_s, :class => "grouped_images", :rel => "group1") %>
		<% end %>
		</td>
		
	</tr>
<% end %>



<%= form_for Painting.new do |f| %>
	<%= f.label :image, "Envoyer les peintures :" %>
	<%= f.file_field :image, multiple: true, name: "painting[image]" %>
<% end %>


<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%;"></div></div>
</div>
</script>



</br></br></br></br>




<script type = "text/javascript">
$(document).ready(function() {

	/* This is basic - uses default settings */
	
	$("a.grouped_images").fancybox();
	
	/* Using custom settings */
	
	$("a#inline").fancybox({
		'hideOnContentClick': true
	});

	/* Apply fancybox to multiple items */
	
	$("a.grouped_images").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	400, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});
	
});
</script>

app/views/paintings/new.html.erb
<h1>Add a Painting</h1>

<%= render 'form' %>

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<p><%= image_tag @painting.image_url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>